// BB + Squeeze + Volume BUY tarayıcısı (Binance Spot + Bybit USDT Perpetual).
// Örnek: BOT_TOKEN=... TELEGRAM_CHAT_ID=... node bb_squeeze_buy_scanner.mjs
// Zaman dilimi varsayılanı: 4 saat (görseldeki örnekle aynı).
import fs from 'node:fs/promises';
import path from 'node:path';

const OUT = path.resolve('bb-squeeze-results');
const INTERVAL = process.env.INTERVAL ?? '4h';
const LIMIT = 220, BB_LEN = 20, BB_MULT = 2, KC_LEN = 20, KC_MULT = 1.5, VOL_LEN = 20, VOL_MULT = 1.5;
const ENABLE_RSI_MACD_CONFIRM = process.env.RSI_MACD_CONFIRM !== 'false';
const fetchJson = async url => { const r = await fetch(url, { signal: AbortSignal.timeout(15000) }); if (!r.ok) throw Error(`${r.status}: ${url}`); return r.json(); };
const mean = xs => xs.reduce((a,b)=>a+b,0)/xs.length;
const sma = (xs,n) => xs.map((_,i)=>i<n-1?null:mean(xs.slice(i-n+1,i+1)));
const std = (xs,n) => xs.map((_,i)=>i<n-1?null:Math.sqrt(mean(xs.slice(i-n+1,i+1).map(x=>(x-mean(xs.slice(i-n+1,i+1)))**2))));
const ema = (xs,n) => { const out=Array(xs.length).fill(null), k=2/(n+1); let v=null; xs.forEach((x,i)=>{v=i===n-1?mean(xs.slice(0,n)):i>=n?(x-v)*k+v:null;out[i]=v});return out; };
const rsi = (closes,n=14) => { const out=Array(closes.length).fill(null);let g=0,l=0;for(let i=1;i<=n;i++){const d=closes[i]-closes[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=n;l/=n;out[n]=l?100-100/(1+g/l):100;for(let i=n+1;i<closes.length;i++){const d=closes[i]-closes[i-1];g=(g*(n-1)+Math.max(d,0))/n;l=(l*(n-1)+Math.max(-d,0))/n;out[i]=l?100-100/(1+g/l):100}return out; };
const atr = (c,n) => sma(c.map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close)):x.high-x.low),n);
const linreg = (xs,n) => xs.map((_,i)=>{if(i<n-1)return null;const y=xs.slice(i-n+1,i+1), x=[...Array(n).keys()],xm=(n-1)/2,ym=mean(y);return ym+x.reduce((s,v,j)=>s+(v-xm)*(y[j]-ym),0)/x.reduce((s,v)=>s+(v-xm)**2,0)*(n-1-xm)});

function signal(c) {
  const close=c.map(x=>x.close), hi=c.map(x=>x.high), lo=c.map(x=>x.low), vol=c.map(x=>x.volume), mid=sma(close,BB_LEN), sd=std(close,BB_LEN), upper=mid.map((v,i)=>v==null?null:v+BB_MULT*sd[i]), lower=mid.map((v,i)=>v==null?null:v-BB_MULT*sd[i]);
  const kc=sma(close,KC_LEN), a=atr(c,KC_LEN), ku=kc.map((v,i)=>v==null?null:v+a[i]*KC_MULT), kl=kc.map((v,i)=>v==null?null:v-a[i]*KC_MULT), sqz=upper.map((v,i)=>v!=null&&lower[i]>kl[i]&&v<ku[i]);
  const base=close.map((_,i)=>{if(i<KC_LEN-1)return 0;const h=Math.max(...hi.slice(i-KC_LEN+1,i+1)),l=Math.min(...lo.slice(i-KC_LEN+1,i+1));return close[i]-(kc[i]+(h+l)/2)/2}), mom=linreg(base,KC_LEN), vs=sma(vol,VOL_LEN), rr=rsi(close), macdLine=ema(close,12).map((v,i)=>v==null?null:v-ema(close,26)[i]), macdSig=ema(macdLine.map(v=>v??0),9), hist=macdLine.map((v,i)=>v==null||macdSig[i]==null?null:v-macdSig[i]);
  const i=c.length-1, breakout=close[i-1]<=upper[i-1]&&close[i]>upper[i], volOk=vol[i]>vs[i]&&vol[i]>vol[i-1]*VOL_MULT, momentum=mom[i]>0&&mom[i]>mom[i-1], recentSqueeze=sqz.slice(Math.max(0,i-10),i).some(Boolean), confirm=!ENABLE_RSI_MACD_CONFIRM||(rr[i]>50&&hist[i]>0&&hist[i]>hist[i-1]);
  return { buy:breakout&&volOk&&momentum&&recentSqueeze&&confirm, upper,lower,mid,sqz,mom,rr,macdLine,macdSig,hist, reasons:{breakout,volOk,momentum,recentSqueeze,confirm} };
}

async function binanceSymbols(){const x=await fetchJson('https://api.binance.com/api/v3/exchangeInfo');return x.symbols.filter(s=>s.status==='TRADING'&&s.isSpotTradingAllowed&&s.quoteAsset==='USDT'&&!/^(USDC|FDUSD|TUSD|USDP|DAI)/.test(s.baseAsset)).map(s=>s.symbol)}
async function binanceCandles(symbol){const rows=await fetchJson(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${INTERVAL}&limit=${LIMIT}`);return rows.map(x=>({time:+x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5]}))}
async function bybitSymbols(){const x=await fetchJson('https://api.bybit.com/v5/market/instruments-info?category=linear&limit=1000');return x.result.list.filter(s=>s.status==='Trading'&&s.quoteCoin==='USDT').map(s=>s.symbol)}
async function bybitCandles(symbol){const map={'4h':'240','1h':'60','1d':'D'};const x=await fetchJson(`https://api.bybit.com/v5/market/kline?category=linear&symbol=${symbol}&interval=${map[INTERVAL]??'240'}&limit=${LIMIT}`);return x.result.list.reverse().map(r=>({time:+r[0],open:+r[1],high:+r[2],low:+r[3],close:+r[4],volume:+r[5]}))}
async function mapPool(items,fn,n=6){let i=0,o=[];await Promise.all([...Array(n)].map(async()=>{while(i<items.length){const v=items[i++];try{const r=await fn(v);if(r)o.push(r)}catch{}}}));return o}
function svg(symbol, venue, c, s) { const W=1200,H=1000,L=65,R=35,top=50,ph=360,rt=475,rh=145,mt=695,mh=145,pw=W-L-R,st=Math.max(0,c.length-90),en=c.length-1,show=c.slice(st),x=i=>L+(i-st)/(en-st)*pw, prices=show.flatMap(a=>[a.high,a.low]),pmin=Math.min(...prices),pmax=Math.max(...prices),py=v=>top+(pmax-v)/(pmax-pmin)*ph,ry=v=>rt+(100-v)/100*rh,my=v=>mt+(1-(v+Math.max(...s.hist.filter(x=>x!=null)))/(2*Math.max(...s.hist.filter(x=>x!=null).map(Math.abs))))*mh, tags=[]; const line=(a,b,c,d,color,w=1)=>`<line x1="${a}" y1="${b}" x2="${c}" y2="${d}" stroke="${color}" stroke-width="${w}"/>`;const pathOf=(a,y,color)=>`<path d="${a.slice(st).map((v,j)=>v==null?'':`${j?'L':'M'}${x(st+j).toFixed(1)},${y(v).toFixed(1)}`).join(' ')}" fill="none" stroke="${color}" stroke-width="1.5"/>`;
  const candles=show.map((v,j)=>{const i=st+j,col=v.close>=v.open?'#16a34a':'#ef4444',cw=Math.max(2,pw/show.length*.6);return line(x(i),py(v.high),x(i),py(v.low),col)+`<rect x="${x(i)-cw/2}" y="${py(Math.max(v.open,v.close))}" width="${cw}" height="${Math.max(1,Math.abs(py(v.open)-py(v.close)))}" fill="${col}"/>`}).join('');
  const sq=show.map((_,j)=>s.sqz[st+j]?`<rect x="${x(st+j)-pw/show.length/2}" y="${top}" width="${pw/show.length}" height="${ph}" fill="#f59e0b" opacity=".14"/>`:'').join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}"><style>text{fill:#e5e7eb;font-family:Arial} .panel{stroke:#344256;stroke-width:1}</style><rect width="100%" height="100%" fill="#07111f"/><rect x="8" y="8" width="${W-16}" height="${H-16}" rx="24" fill="#091525" class="panel"/><text x="${L}" y="30" font-size="19" font-weight="bold">${symbol} — ${venue} — ${INTERVAL}</text><text x="${L}" y="48" font-size="12" fill="#a5b4c6">BB SQUEEZE · FİYAT TREND · RSI TREND · MACD</text><rect x="${L}" y="${rt-30}" width="${pw}" height="${rh+35}" fill="#091525" class="panel"/><rect x="${L}" y="${mt-30}" width="${pw}" height="${mh+35}" fill="#091525" class="panel"/>${sq}${candles}${pathOf(s.upper,py,'#1d9bf0')}${pathOf(s.lower,py,'#1d9bf0')}${pathOf(s.mid,py,'#94a3b8')}<text x="${L}" y="${rt-12}" font-size="15">RSI(14) / RSI TREND</text>${[30,50,70].map(v=>line(L,ry(v),W-R,ry(v),'#475569')).join('')}${pathOf(s.rr,ry,'#a78bfa')}<text x="${L}" y="${mt-12}" font-size="15">MACD(12,26,9)</text>${s.hist.slice(st).map((v,j)=>v==null?'':`<rect x="${x(st+j)-2}" y="${my(Math.max(0,v))}" width="4" height="${Math.abs(my(v)-my(0))}" fill="${v>=0?'#22c55e':'#ef4444'}"/>`).join('')}${pathOf(s.macdLine,my,'#38bdf8')}${pathOf(s.macdSig,my,'#f59e0b')}<rect x="${x(en)-34}" y="${py(c[en].low)+15}" width="68" height="22" rx="4" fill="#22c55e"/><text x="${x(en)-24}" y="${py(c[en].low)+30}" font-size="12" fill="#07111f">BUY</text><rect x="8" y="870" width="${W-16}" height="122" rx="0" fill="#ffffff"/><text x="26" y="900" font-size="18" fill="#0f172a">⭐ ${venue} 4S BUY SİNYALİ</text><text x="26" y="925" font-size="15" fill="#0f172a">Parite: ${symbol}</text><text x="26" y="950" font-size="15" fill="#0f172a">Fiyat: ${c[en].close} | BB Squeeze + Hacim + RSI/MACD teyidi</text><text x="26" y="975" font-size="13" fill="#475569">Grafik: Mum + BB/SQ + Fiyat Trend + RSI Trend + MACD</text></svg>`; }

await fs.mkdir(OUT,{recursive:true});
const venues=[['BINANCE_SPOT',binanceSymbols,binanceCandles],['BYBIT_LINEAR',bybitSymbols,bybitCandles]];let found=[];
for(const [name,getSymbols,getCandles] of venues){try{const symbols=await getSymbols();console.log(`${name}: ${symbols.length} parite taranıyor`);const hits=await mapPool(symbols,async symbol=>{const candles=await getCandles(symbol),state=signal(candles);return state.buy?{name,symbol,candles,state}:null});found.push(...hits)}catch(e){console.error(`${name} erişilemedi: ${e.message}`)}}
for(const h of found){const file=`${h.name}_${h.symbol}_${INTERVAL}.svg`;await fs.writeFile(path.join(OUT,file),svg(h.symbol,h.name,h.candles,h.state));h.image=file;delete h.candles;delete h.state}await fs.writeFile(path.join(OUT,'signals.json'),JSON.stringify({scannedAt:new Date().toISOString(),interval:INTERVAL,signals:found},null,2));console.log(JSON.stringify(found,null,2));
